"""Add rating column to Review model

Revision ID: 05ed6b39b774
Revises: 2ac0886480b2
Create Date: 2024-02-09 19:53:32.201086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ed6b39b774'
down_revision = '2ac0886480b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
